name: build
on: 
  workflow_dispatch
#  push:
#    paths:
#      - 'src/Sample/**'
#    tags:
#      - '*'
#    branches: [ publish ]
#  pull_request:
#    branches: [ publish ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:    
      # リポジトリのチェックアウト
      - uses: actions/checkout@v2
    
      # dotnetのインストール (3.1)
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      # ndextのインストール @https://docs.nextdesign.app/extension/docs/tools/ndext/installation
      - name: Setup NDext
        run: |
          dotnet tool install --global NDExt
          ndext install

      # ビルドとパッケージング
      - name: Build & Pack (NDExt)
        run: |
          $pkg_dir = (Convert-Path .) + "packages"
          foreach ($dir in $(Get-ChildItem * | ? { $_.PSIsContainer }))
          {
            Push-Location $dir
            if ($(Get-ChildItem *.csproj -Recurse | Test-Path))
            {
              $xml_doc = [xml](cat $(Get-ChildItem *.csproj -Recurse) -enc utf8)
              $xml_nav = $xml_doc.CreateNavigator()
              $pkg_name =  $xml_nav.Select("//PackageId")
              $pkg_name += "."
              $pkg_name += $xml_nav.Select("//Version") 
              $pkg_name += ".nupkg"

              if (!$(Test-Path $pkg_name))
              {
                ndext pack o $pkg_dir
              }

            }
            Pop-Location
          }

#      NDExtを使用しているパッケージが前提
#      - name: Build & Pack (proj)
#        run: |
#          cd ./src/Package
#          dotnet publish
#          nuget pack .\sample_ndext\Package.1.0.0.nuspec -OutputDirectory ../../packages

#      - name: Build & Pack (sample)
#        run: |
#          cd ./src/Sample
#          nuget pack MyPackage.1.0.0.nuspec -OutputDirectory ../../packages

      # パッケージのコミット
      - name: Commit & Push Packages
        if: ${{ always() }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          repository: ./packages/

          skip_checkout: true
          create_branch: true

          # Optional commit user and author settings
          commit_user_name: My GitHub Actions Bot # defaults to "GitHub Actions"
          commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
