name: check_outputs
on: 
  workflow_dispatch

env: 
  VERSION: 2.0

jobs:
  Build1:
    runs-on: windows-latest
    steps:
    - name: notify
      id: update-project-version
      run: |
        Write-Output ${{ env.VERSION }}
        $GITHUB_OUTPUT = new_version_no=12 

    - name: second
      run: | 
        Write-Output ${{ steps.update-project-version.outputs.new_version_no }}
