name: check_status
on: 
  workflow_dispatch

jobs:
  Build1:
    runs-on: ubuntu-latest
    steps:
    - run: |
      # Install chocolatey
      if (! (Get-Command "choco" -ErrorAction Ignore)) {
          Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      }
      $env:ChocolateyInstall = Convert-Path "$((Get-Command 'choco').path)\..\.."
      Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"

      # NodeJS / yarn
      cinst nodejs-lts -y
      cinst yarn -y

      # Update PATH environment
      refreshenv        

  Build2:
    runs-on: ubuntu-latest
    needs: Build1
    steps:
    - run: echo Build2

  Build3:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
    - name: notify
      run: |
        echo ${{job.status}}
        echo ${{github.action_status}}

  Build4:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: Build2
    steps:
    - run: |
        echo ${{job.status}}
        echo ${{github.action_status}}

  Build5:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: Build2
    steps:
    - run: |
        echo ${{job.status}}
        echo ${{github.action_status}}
