name: check_status
on: 
  workflow_dispatch

env: 
  VERSION: 2.0

jobs:
  Build1:
    runs-on: windows-latest
    steps:
    - name: notify
      run: echo ${{env.VERSION}}

  Build2:
    runs-on: ubuntu-latest
    needs: Build1
    steps:
    - run: echo ${{env.VERSION}}

  Build3:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
    - name: notify
      run: |
        echo ${{job.status}}
        echo ${{github.action_status}}

  Build4:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: Build2
    steps:
    - run: |
        echo ${{job.status}}
        echo ${{github.action_status}}

  Build5:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: Build2
    steps:
    - run: |
        echo ${{job.status}}
        echo ${{github.action_status}}
