name: diff
on: 
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    
    steps:    
      # リポジトリのチェックアウト
      - uses: actions/checkout@v2
    
      # dotnetのインストール (3.1)
      - name: Setup kazoechao
        run: |
          wget http://www.vector.co.jp/soft/dl/winnt/prog/se251853.html

