name: diff
on: 
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    runs-on: windows-latest
    
    steps:    
      # リポジトリのチェックアウト(ベース)
      - uses: actions/checkout@v2
        with: 
          path: base
          ref: ${{github.base_ref}}
    
      # リポジトリのチェックアウト(マージ対象)
      - uses: actions/checkout@v2
        with: 
          path: ${{github.head_ref}}

      # kazoeciao のインストール (latest)
      - name: Setup kazoeciao
        run: |
          Invoke-WebRequest -Uri "https://ftp.vector.co.jp/71/79/3284/kazoeciao.zip" -Outfile ".\kazoeciao.zip"
          Expand-Archive -Path .\kazoeciao.zip -DestinationPath .\kazoeciao
          Set-Location .\kazoeciao
          mkdir .\tmp
          if (Test-Path ../target/setting/autoexec.cas)
          {
            .\kazoeciao.exe /a../target/setting/autoexec.cas | out-null
            Set-Location tmp
            cat .\*.csv
          }
