name: diff
on: 
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    
    steps:    
      # リポジトリのチェックアウト(ベース)
      - uses: actions/checkout@v2
        with: 
          path: base
          ref: main
    
      # リポジトリのチェックアウト(マージ対象)
      - uses: actions/checkout@v2
        with: 
          path: target

      # kazoeciao のインストール (latest)
      - name: Setup kazoeciao
        run: |
          Invoke-WebRequest -Uri "https://ftp.vector.co.jp/71/79/3284/kazoeciao.zip" -Outfile ".\kazoeciao.zip"
          Expand-Archive -Path .\kazoeciao.zip -DestinationPath .\kazoeciao
          ls
          cd .\base
          ls
          cd ..\
          cd .\kazoeciao
          mkdir .\tmp
          if (Test-Path ../base/setting/sample.cas)
          {
            .\kazoeciao.exe /a../base/setting/sample.cas | out-null
            cd tmp
            cat .\*.csv
          }
