name: publish

on:
  workflow_dispatch
  push:
    branches: 
      - publish

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:    
      # リポジトリのチェックアウト
      - uses: actions/checkout@v2
    
      # dotnetのインストール (3.1)
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      # Nugetサーバへのnupkgの登録
      - name: Publish to GitHub Packages
        run: |
          cd ./packages
          dotnet nuget add source "https://nuget.pkg.github.com/maegawa-h/index.json" -n "github" -u ${{secrets.GH_PACKAGES_USER}} -p ${{secrets.GH_PACKAGES_PAT}} --store-password-in-clear-text
          dotnet nuget push "*.nupkg" --api-key ${{secrets.GH_PACKAGES_PAT}} --source "github" --skip-duplicate
