name: .NET

on:
  push:
    paths:
      - 'src/Sample/**'
#    tags:
#      - '*'
#    branches: [ publish ]
#  pull_request:
#    branches: [ publish ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:    
      - uses: actions/checkout@v2
    
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

#      - name: Install dependencies
#        run: |
#          dotnet restore
      
      - name: Build
        run: |
          cd ./src/Sample
          nuget pack MyPackage.1.0.0.nuspec -OutputDirectory ../../packages
      
#      - name: Pack
#        run: |
#          dotnet pack MyGreatLib.csproj -o artifacts/

#      - uses: actions/upload-artifact@v1
#        with:
#          name: artifacts
#          path: artifacts

      - name: Publish to GitHub Packages
        run: |
          cd ./packages
          dotnet nuget add source "https://nuget.pkg.github.com/maegawa-h/index.json" -n "github" -u maegawa-h -p ${{secrets.GH_PACKAGES_PAT}} --store-password-in-clear-text
          dotnet nuget push "*.nupkg" --api-key ${{secrets.GH_PACKAGES_PAT}} --source "github" --skip-duplicate

      - name: Commit & Push Packages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          repository: ./packages/

          skip_checkout: true
          create_branch: true

          # Optional commit user and author settings
          commit_user_name: My GitHub Actions Bot # defaults to "GitHub Actions"
          commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

      # Start a Slack workflow using a webhook trigger
      # https://github.com/slackapi/slack-github-action
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
            {
              "text": ":github: ビルド結果: ${{ job.status }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":github: ビルド結果: ${{ job.status }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Author: <https://github.com/${{ github.event.sender.login }}|@${{ github.event.sender.login }}>"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{secrets.GH_SLACK_WH}}

#        run: |
#          cd ./packages
#          git remote set-url origin https://github-actions:${secrets.GITHUB_TOKEN}@github.com/${secrets.GITHUB_REPOSITORY}
#          git config user.name "sample"
#          git config user.email "sample@sample.com"
#          if ! git diff --exit-code --quiet
#          then
#            git add .
#            git commit -m "message"
#            git pull
#            git push origin HEAD:${secrets.GITHUB_REF}
#          fi
