name: summaries

on: 
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:    
      - name: Generate list using Markdown
        run: |
          echo "<h1>This is the lead in sentence for the list</h1>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY

          echo "<div class=""iframe-wrap""><iframe width=""675"" height=""380"" src=""https://www.youtube.com/embed/_AQXQDjw7Y8?start=5&amp;end=10&amp;"" frameborder=""1"" allow=""accelerometer; autoplay; encrypted‑media; gyroscope; picture‑in‑picture"" allowfullscreen></iframe>" >> $GITHUB_STEP_SUMMARY

